  scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 30s
      static_configs:
        - targets: ['localhost:9091']
    - job_name: 'node'
      scrape_interval: 15s
      static_configs:
        - targets: ['localhost:9191']
        labels:
          group: 'test'
